### PR TITLE
Fix PVG settings stage numbers

### LINKED ISSUE #1920: Visual Bug with Earlyshutoff / last stage
KSP_x64_2024-11-22_09-50-10
KSP_x64_2024-11-22_09-50-25

[R-7 Super.zip](https://github.com/user-attachments/files/17868661/R-7.Super.zip)

Here is 2 screenshots and a craft file from RP-1 showing it

### PR DESCRIPTION
**Pull request by Nazfib**
When multiple stages in the Δv stats window have the same KSP stage number, the (unguided) and (optimize) labels get applied to the wrong stage(s). This commit changes the window to apply the labels to the stage with the correct KSP stage, which may not be the same as the index in the vacStats list.

Fix #1920.

### CODE REVIEW

File: MechJeb2/MechJebModuleAscentPVGSettingsMenu.cs [hunk 1]
```diff
@@ -64,9 +66,9 @@ protected override void WindowGUI(int windowID)
 
                     GUILayout.BeginHorizontal();
                     GUILayout.Label($"{stats.KSPStage,3} {stats.DeltaV:##,###0} m/s");
-                    if (_ascentSettings.UnguidedStages.Contains(mjPhase))
+                    if (_ascentSettings.UnguidedStages.Contains(stats.KSPStage))
                         GUILayout.Label(" (unguided)");
-                    if (_ascentSettings.OptimizeStage == mjPhase)
+                    if (_ascentSettings.OptimizeStage == stats.KSPStage)
```
Comment (lamont-granquist) [inline MechJeb2/MechJebModuleAscentPVGSettingsMenu.cs:71]: this line might cause a problem if it matches multiple stages.  i don't know that it is fixable here, though.

really the fix that needs to happen is that the FFS needs the asymmetric burnout code added to it, in order to suppress the extra stages.
